### PR TITLE
Update to new compilers

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
Error:
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/conda/feedstock_root/build_artifacts/r-bpca_1552658447409/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/library/rgl/libs/rgl.so':
  libGL.so.1: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘rgl’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error: 	Loading rgl's DLL failed. 
Error : package ‘rgl’ could not be loaded

@dpryan79 Started to update a bunch of packages that use r-rgl... they all would need the `LD_LIBRARY_PATH=...` set to build and also later to use the package... looks like we should fix that in r-rgl instead of pushing that to the user of the package

**Comment by dpryan79** [comment]
On the bioconda side we have an extended docker image that includes libGL. I'm not sure how to do that with conda-forge, since libGL is a system dependency.

**Comment by dpryan79** [comment]
BTW, users shouldn't need to set `LD_LIBRARY_PATH`, libGL will be in some default location on their system. This trick should only be needed during CI testing since it's in a non-standard location.

As an example:

```
dpryan@dpryan-X555LN:~/miniconda3/envs/r-rgl$ ldd -r lib/R/library/rgl/libs/rgl.so 
	linux-vdso.so.1 (0x00007ffeb39cf000)
	libGLU.so.1 => /home/dpryan/miniconda3/envs/r-rgl/lib/R/library/rgl/libs/../../../../libGLU.so.1 (0x00007f4760ea6000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f4760ac9000)
        ...
```

**Comment by dbast** [comment]
@dpryan79 Ok... tried it. Still failing ... hm, anything missing from the workaround?

**Comment by dpryan79** [comment]
@dbast From what I can tell, anything using libGL requires the following CDTs:

```
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libxfixes') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('mesa-dri-drivers') }}
```

**Comment by dpryan79** [comment]
Oh, and the yum stuff isn't needed as far as I know.

**Comment by dpryan79** [comment]
@dbast See my changes. This is one of the headaches surrounding CDTs in my mind (not that I have a better way of doing it).

**Comment by dbast** [comment]
@dpryan79 Cool, thanks!

**Comment by dbast** [comment]
ok. if we agree on that solution we can merge it and apply it to the other packages which depend on r-rgl...

**Comment by dpryan79** [comment]
AFAIK it's the only solution for packages that end up depending on libGL, so :+1: from me.

**Pull request merged**
